name = "CausalInference"
uuid = "8e462317-f959-576b-b3c1-403f26cec956"
authors = ["Moritz Schauer <moritzschauer@web.de>"]
version = "0.8.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"

[compat]
Combinatorics = "1.0"
Distances = "0.8, 0.9, 0.10"
Distributions = "0.22, 0.23, 0.24, 0.25"
NearestNeighbors = "0.4"
SpecialFunctions = "1.8, 2.0"
Tables = "1.6"
TikzGraphs = "1.3"
julia = "1.5, 1.6"
MetaGraphs = "0.7"
Graphs = "1.5"


[extras]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StatsBase"]
